on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.16'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          only-new-issues: true
      - run: go test -race ./...
